### ISSUE TITLE
Feature request: support Python >3.3

### ISSUE THREAD

**Issue by daveuu** [biocore/biom-format#644]
3.5 is now out. I'm wondering whether there are known incompatibilities with >3.3 or if those versions haven't been tested yet ("unknown unknowns")?

**Comment by wasade** [comment]
There is: the pyqi dependency. We've been meaning to move to click but are
short on developer effort right now. We'd greatly welcome a PR though as
we're really excited about Python 3

**Comment by gregcaporaso** [comment]
Note that biom doesn't work with Python 3.3 either:

```
$ python
Python 3.3.5 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:22:11)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import biom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gregcaporaso/.conda/envs/uc2biom/lib/python3.3/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/home/gregcaporaso/.conda/envs/uc2biom/lib/python3.3/site-packages/biom/table.py", line 182, in <module>
    from itertools import izip
ImportError: cannot import name izip
```

**Comment by wasade** [comment]
Likely some other py3 incompatibilities have slipped through as a result of not formally checking

**Comment by gregcaporaso** [comment]
@wasade, @jairideout and @ebolyen are going to try to sprint on this on Monday. The plan would be to keep the CLI backward compatible, but under the hood drop pyqi in favor of click. At that point, biom-format >= 2.1.5 < 2.2.0 would support Python 2.7 and Python 3.5(?). Does that sound right?

**Comment by wasade** [comment]
:+1:

**Comment by gregcaporaso** [comment]
This is basically the milestone, and a duplicate of #647. Closing.
