### ISSUE TITLE
Fail to install/compile with python 3.7.1

### ISSUE THREAD

**Issue by fungs** [biocore/biom-format#804]
Installing version 2.1.7 via pip gives the following error:

biom/_filter.c:8393:19: Error: »PyThreadState« has no element named »exc_type«
[...]

Steps to reproduce:

    conda create -n biom python=3.7 numpy scipy pandas
    source activate biom
    pip install biom-format

I had to re-generate all .c extensions using cython 0.29.2:

    find . -iname "*.pyx" | xargs -n 1 cython
    python setup.py build

Best,
Johannes

**Comment by ElDeveloper** [comment]
If it is the case that cython is backwards-compatible, then that is a 
really good solution!

**Comment by jolespin** [comment]
Is there any progress on this?

**Comment by eladkehat** [comment]
I had the same problem.
If it's any help, I was able to install an older version: `biom-format==2.1.5`

**Comment by HayleyDeckers** [comment]
Same issue on Windows with a clean install of the latest Python 3 and Visual Studio. I installed Cython too but it did not automatically regenerate the files yet. @eladkehat 's suggestion worked as a work-around.

**Comment by wasade** [comment]
Should be fixed in #825
