### ISSUE TITLE
BIOM 1.3.1 can't read BIOM tables created by QIIME

### ISSUE THREAD

**Issue by mlangill** [biocore/biom-format#613]
I realize BIOM (and QIIME) have moved to v2.1.x but I expected that BIOM 1.3.1 would still be able to read these new tables? 

From the PICRUSt mailing list there have been several users that are getting the same error:

```
table = parse_biom_table(biom_f)
  File "/home/mlangill/.virtualenvs/picrust_biom2/local/lib/python2.7/site-packages/biom_format-1.3.1-py2.7.egg/biom/parse.py", line 323, in parse_biom_table
    t = parse_biom_table_str(table_str, constructor=constructor)
  File "/home/mlangill/.virtualenvs/picrust_biom2/local/lib/python2.7/site-packages/biom_format-1.3.1-py2.7.egg/biom/parse.py", line 591, in parse_biom_table_str
    f = BIOM_TYPES.get(json_table['type'].lower(), None)
AttributeError: 'NoneType' object has no attribute 'lower'
```

The OTU table is in json format, but if I convert --to-json then the resulting otu table works with BIOM 1.3.1:

```
biom convert -i otu_table.biom -o otu_table_converted.biom --to-json --table-type "Taxon table"
```

Example of problematic OTU table:
https://www.dropbox.com/s/q9sam8wndss8tda/otu_table.biom?dl=1

**Comment by wasade** [comment]
I think it was accidentally working (before)[https://github.com/biocore/biom-format/commit/215479a14e5d41879ef9430787fbe8d9873aa713] by just setting "None", the end effect is it would default to "otu table".

**Comment by wasade** [comment]
I think this is actually a bug in 1.3.1 as I look closer at it, where `parse_biom_table` should not be calling `.lower()` on that field. Our options are limited in 2.1.x as I do not think setting a default table type is a good thing in a minor release, and any other choice breaks the roundtrip ability of 2.1.x which is not good. Basically, I think we need to do a 1.3.2 release, which is annoying.

**Comment by vaxherra** [comment]
Hi,
it seems that I've stumbled upon the same problem while using picrust and biom 1.3.1. It is solved by using 1.3.2 version?

**Comment by wasade** [comment]
We never did a 1.3.2 release as its demand is really low. I recommend using the workaround that @mlangill noted

**Comment by manasishah86** [comment]
Hi, I am encountering the same problem. 
I converted a QIIME OTU table to biom using biom convert in version 1.3.1. After PICRUSt analysis, when I would like to check the contents from a biom output, I cannot convert it to a standard .txt format. The solution by @mlangill does not work as 

> --to-json
is not a valid option in the biom-format 1.3.1 version I currently have installed. What other possible options could I try? 
Thanks,
Manasi

**Comment by wasade** [comment]
@manasishah86, running `biom convert --help` will provide options. I believe for that version of BIOM, it should be possible to convert to tab delimited with:

```bash
biom convert -i table.biom -o table.from_biom.txt -b
```

...and to go to BIOM with:

```
biom convert -i table.txt -o table.from_txt.biom --table-type="otu table"
```

**Comment by wasade** [comment]
I'm closing this issue as PICRUSt now directly supports BIOM 2.x, and no one has expressed interest in putting together a microrelease off of 1.3.2.
